---
title: "Scrapy Project - Word Cloud Experiments"
author: "TheMitchWorksPro"
date: "8/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Word Clouds Based on CR Computer Reviews

Word Cloud based on Positive Reviews (Reviewer gave score of 2.5 or more on scale of 1 to 5).


```{r setupLibs, warning=FALSE}
# http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know

# Install
# install.packages("tm")  # for text mining
# install.packages("SnowballC") # for text stemming
# install.packages("wordcloud") # word-cloud generator 
# install.packages("RColorBrewer") # color palettes
# Load

library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")

```

Source text files:

```{r}

# text1 <- readLines(file.choose())  # manually selected path:
text1 <- readLines("./corpus/target/word_cloud_txt_positive.txt") # positive reviews

```

Begin processing ...

```{r}
# read file for corpus:
docs <- Corpus(VectorSource(text1))

```

Inspect documents:

```{r}

inspectRetrn  <- inspect(docs)  # run this variable to view all of the documents

```
Text Cleaning:

```{r}

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")  # replacing characters to establish true "words for the process"
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("use", "will", "time", "tech", "hour", "key", "even", "well",
                                    "year", "bought", "purcha", "also", "much", "just", "thing", "system",
                                    "without", "take", "size", "two", "second", "set", "first", "third",
                                    "can", "one", "get","buy", "need", "lot", "product", "now", "long", "comput", "consid",
                                    "type", "model", "reason", "less", "never", "close", "review", "general", "way",
                                    "ever", "seem", "got", "note", "howev", "around", "made", "alway", "still", "everi", "back",
                                    "almost", "combin", "tri", "anythi", "enough")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
docs <- tm_map(docs, stemDocument)

```


Build a term-document matrix:

```{r}

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 200)

```
Generate the Word cloud

```{r}

set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

```

```{r}

barplot(d[1:20,]$freq, las = 2, names.arg = d[1:20,]$word,
        col ="darkgreen", main ="Most Fequent Words - Positive Reviews",
        ylab = "Word frequencies")

```

